# apps/admin-web/Dockerfile
FROM node:20-bullseye-slim AS build
WORKDIR /app

COPY package.json ./
COPY package-lock.json* ./

# 🔑 КЛЮЧЕВАЯ СТРОКА
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80